---
title: "Depression among patients living with diabetes - Wrangling"
author: "Eric Anku"
format: html
---

```{r import-libraries}
pacman::p_load(
  tidyverse, # Data wrangling
  foreign, # Load SPSS dataset
  janitor, # Clean data
  rio, # Import and Export dataset
  here, # File management
  skimr, # Skim data
  finalfit # Labelling data
)
```

```{r import-dataset}
df <- import(here("data", "data.sav"))
head(df)
```

```{r mutate-depression-functionality}
df <- df |>
  mutate(
    functionality = (
      ff1 + ff2 + ff3 + ff4 + ff5
    ) |>
      ff_label("Family fuctionality"),
    depression = (
      phq1 + phq2 + phq3 + phq4 + phq5 + phq6 + phq7 + phq8 + phq9
    ) |>
      ff_label("Depression assessment")
  )
```

```{r categorise-functionality-depression}
df <- df |>
  mutate(
    functionality_cat = 
    case_when(
      functionality <= 7 ~ "Dysfunctional",
      functionality > 7  ~ "Highly functional"
    ) |>
      ff_label("Functionality"),
    depression_cat = 
      case_when(
        depression <= 4 ~ "Normal",
        depression > 4 ~ "Depression"
      ) |>
      ff_label("Depression")
  )
```


```{r characterise-labels}
df <- characterize(df)
df <- factorize(df, coerce_character = TRUE)
head(df)
```

```{r glimpse-data}
glimpse(df)
```
```{r}
# Remove functionality and depression variables
df <- df |>
  select(
    -c(
    depression,
    functionality
  )
  )
```

```{r skim-data}
skim(df)
```
```{r mutate-variables}
df <- df |>
  mutate(
    bmi = body_weight / (height)**2 |>
      ff_label("Body mass index (kg/m^2"),
    whr = waist_circumference / hip_circumference |>
      ff_label("Waist-to-hip ratio"),
    sbp = (bp_sbp2 + bp_sbp3) / 2 |>
      ff_label("Systolic blood pressure (mmHg)"),
    dbp = (bp_dbp2 + bp_dbp3) / 2 |>
      ff_label("Diastolic blood pressure (mmHg)"),
    hbaic_cat = case_when(
      hba1c_value < 7 ~ "Good control",
      hba1c_value >= 7 ~ "Poor control"
    ) |>
      ff_label("HBA1C categories"),
    education = education |>
      fct_relevel(
        "No formal education",
        "Primary school",
        "Middle school/JSS/JHS",
        "Secondary school/SSS/SHS",
        "Tertiary and above"
      ),
    age = age |> ff_label("Age (years)"),
    age_group = case_when(age <= 60 ~ "Below 60 years", 
                          .default = "Above 60 years"),
    mar_stat_three = fct_recode(
      marital_status,
      "Single" = "Single/never maried",
      "Single" = "Widowed",
      "Single" = "Divorced/Separated"
    ),
    mar_stat_two = fct_recode(
      marital_status,
      "Not married" = "Single/never maried",
      "Not married" = "Widowed",
      "Not married" = "Divorced/Separated",
      "Not married" = "Cohabiting"
    )
  )
```



```{r waist-hip-ratio}
male_cut_off <- 0.9
female_cut_off <- 0.85

df <- df |>
mutate(
  whr_cat = case_when(
  sex == "Male" & whr <= male_cut_off ~ "Normal",
  sex == "Female" & whr <= female_cut_off ~ "Normal",
  .default = "High"
) |>
  ff_label("WHR categories")
)
```



```{r bmi-category}
df <- df |>
  mutate(
    bmi_cat = case_when(
      bmi < 18.5 ~ "Underweight",
      bmi >= 18.5 & bmi <= 24.9 ~ "Normal",
      bmi >= 25 & bmi <= 29.9 ~ "Overweight",
      .default = "Obesity"
    ) 
  )
```

```{r relevel-bmi-cat}
df <- df |>
  mutate(
    bmi_cat = factor(bmi_cat) |>
      fct_relevel(
        "Underweight",
        "Normal",
        "Overweight",
        "Obesity"
      ) |> 
      ff_label("BMI categories")
  )
```

```{r bp-cat}
df <- df |>
  mutate(
    bp_cat = 
      case_when(
        sbp <= 140 & dbp <= 80 ~ "Good BP control",
        .default = "Poor BP control"
      ) |>
      ff_label("Blood pressure categories")
  )
```


```{r mutate-age}
# Replace the patient's age from 80 to 81
df <- df |>
  mutate(age = ifelse(id == "DM/083", 80, age))
```


```{r create-subsets}
# Demographics
demographics <- 
  df |>
  select(
    sex,
    age,
    age_group,
    education,
    marital_status,
    religious_background,
    employment_status,
    place_of_permanent_residence,
    monthly_income,
    mar_stat_two,
    mar_stat_three,
    functionality_cat,
    depression_cat,
    hbaic_cat
  )

# Health related characteristics
health <- 
  df |>
  select(
    sex,
    hba1c_value,
    body_weight,
    height,
    bmi,
    bmi_cat,
    waist_circumference,
    hip_circumference,
    sbp,
    dbp,
    bp_cat,
    whr_cat,
    duration_diabetes,
    treatment_diabetes,
    functionality_cat,
    depression_cat,
    hbaic_cat
  )

# Family functionality
fam_func <- 
  df |>
  select(
    sex,
    ff1,
    ff2,
    ff3,
    ff4,
    ff5,
    functionality_cat
  )

# Depression
depress <- 
  df |>
  select(
    sex,
    phq1,
    phq2,
    phq3,
    phq4,
    phq5,
    phq6,
    phq7,
    phq8,
    phq9,
    depression_cat
  )
```

```{r export-clean-data}
# Main dataset
export(df, here("data", "clean_data.RData"))
export(df, here("data", "clean_data.csv"))

# Demographics
export(demographics, here("data", "demos.RData"))

# Health related characteristics
export(health, here("data", "health.RData"))

# Family functionality
export(fam_func, here("data", "family.RData"))

# Depression
export(depress, here("data", "depression.RData"))
```

